openapi: 3.1.0
info:
  title: Compliance
  description: Needs a description.
paths:
  /compliance:
    description: Provides operations to manage the compliance singleton.
    get:
      tags:
        - compliance.compliance
      summary: Get compliance
      operationId: compliance.compliance.GetCompliance
      parameters:
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.compliance'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - compliance.compliance
      summary: Update compliance
      operationId: compliance.compliance.UpdateCompliance
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.compliance'
        required: true
      responses:
        2XX:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.compliance'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  /deviceManagement/complianceManagementPartners:
    description: >-
      Provides operations to manage the complianceManagementPartners property of
      the microsoft.graph.deviceManagement entity.
    get:
      tags:
        - deviceManagement.complianceManagementPartner
      summary: Get complianceManagementPartners from deviceManagement
      description: The list of Compliance Management Partners configured by the tenant.
      operationId: deviceManagement.ListComplianceManagementPartners
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          $ref: >-
            #/components/responses/microsoft.graph.complianceManagementPartnerCollectionResponse
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - deviceManagement.complianceManagementPartner
      summary: >-
        Create new navigation property to complianceManagementPartners for
        deviceManagement
      operationId: deviceManagement.CreateComplianceManagementPartners
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.complianceManagementPartner'
        required: true
      responses:
        2XX:
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/microsoft.graph.complianceManagementPartner
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  /deviceManagement/complianceManagementPartners/{complianceManagementPartner-id}:
    description: >-
      Provides operations to manage the complianceManagementPartners property of
      the microsoft.graph.deviceManagement entity.
    get:
      tags:
        - deviceManagement.complianceManagementPartner
      summary: Get complianceManagementPartners from deviceManagement
      description: The list of Compliance Management Partners configured by the tenant.
      operationId: deviceManagement.GetComplianceManagementPartners
      parameters:
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        2XX:
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/microsoft.graph.complianceManagementPartner
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - deviceManagement.complianceManagementPartner
      summary: >-
        Update the navigation property complianceManagementPartners in
        deviceManagement
      operationId: deviceManagement.UpdateComplianceManagementPartners
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.complianceManagementPartner'
        required: true
      responses:
        2XX:
          description: Success
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/microsoft.graph.complianceManagementPartner
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - deviceManagement.complianceManagementPartner
      summary: >-
        Delete navigation property complianceManagementPartners for
        deviceManagement
      operationId: deviceManagement.DeleteComplianceManagementPartners
      parameters:
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    parameters:
      - name: complianceManagementPartner-id
        in: path
        description: The unique identifier of complianceManagementPartner
        required: true
        schema:
          type: string
        x-ms-docs-key-type: complianceManagementPartner
  /deviceManagement/complianceManagementPartners/$count:
    description: Provides operations to count the resources in the collection.
    get:
      tags:
        - deviceManagement.complianceManagementPartner
      summary: Get the number of the resource
      operationId: deviceManagement.complianceManagementPartners.GetCount-eeb1
      parameters:
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
      responses:
        2XX:
          $ref: '#/components/responses/ODataCountResponse'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
components:
  schemas:
    microsoft.graph.compliance:
      title: compliance
      required:
        - '@odata.type'
      type: object
      properties:
        '@odata.type':
          type: string
    microsoft.graph.complianceManagementPartner:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: complianceManagementPartner
          required:
            - '@odata.type'
          type: object
          properties:
            androidEnrollmentAssignments:
              type: array
              items:
                $ref: >-
                  #/components/schemas/microsoft.graph.complianceManagementPartnerAssignment
              description: User groups which enroll Android devices through partner.
            androidOnboarded:
              type: boolean
              description: Partner onboarded for Android devices.
            displayName:
              type: string
              description: Partner display name
              nullable: true
            iosEnrollmentAssignments:
              type: array
              items:
                $ref: >-
                  #/components/schemas/microsoft.graph.complianceManagementPartnerAssignment
              description: User groups which enroll ios devices through partner.
            iosOnboarded:
              type: boolean
              description: Partner onboarded for ios devices.
            lastHeartbeatDateTime:
              pattern: >-
                ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
              type: string
              description: >-
                Timestamp of last heartbeat after admin onboarded to the
                compliance management partner
              format: date-time
            macOsEnrollmentAssignments:
              type: array
              items:
                $ref: >-
                  #/components/schemas/microsoft.graph.complianceManagementPartnerAssignment
              description: User groups which enroll Mac devices through partner.
            macOsOnboarded:
              type: boolean
              description: Partner onboarded for Mac devices.
            partnerState:
              $ref: >-
                #/components/schemas/microsoft.graph.deviceManagementPartnerTenantState
            '@odata.type':
              type: string
          description: Compliance management partner for all platforms
      x-ms-discriminator-value: '#microsoft.graph.complianceManagementPartner'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      style: form
      explode: false
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      style: form
      explode: false
      schema:
        minimum: 0
        type: integer
    search:
      name: $search
      in: query
      description: Search items by search phrases
      style: form
      explode: false
      schema:
        type: string
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      style: form
      explode: false
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      style: form
      explode: false
      schema:
        type: boolean
  examples: {}
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/microsoft.graph.ODataErrors.ODataError'
    ODataCountResponse:
      description: The count of the resource
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/ODataCountResponse'
